---
abstract: 'Look up the network interface vendor by its MAC'
author:
  - 'brian d foy <bdfoy@cpan.org>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-MAC-Vendor
no_index:
  directory:
    - t
    - inc
resources:
  repository: https://github.com/briandfoy/net-mac-vendor
version: 1.22
