--- #YAML:1.0
name:                Net-MAC-Vendor
version:             1.18
abstract:            look up the network interface vendor by MAC
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    LWP::Simple:                   0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
author:
    - brian d foy <bdfoy@cpan.org>
